### ISSUE TITLE
Snowfighter Most Requested font too large

### ISSUE THREAD

**Issue by danfox01** [martypowell/baltimorecountymd.gov-assets#5] opened 2015-06-25 14:48 UTC
http://staging.baltimorecountymd.gov/homepageredesign/Agencies/publicworks/SnowFighter/index.html

![image](https://cloud.githubusercontent.com/assets/13049389/8357198/a1214902-1b27-11e5-899f-915b9b750ec0.png)

**Comment by martypowell** [comment] 2015-06-25 14:51
Duplicate of #1

**Comment by martypowell** [comment] 2015-06-26 14:08
Fixed in issue #1

**Closed by martypowell** 2015-06-26 14:08 UTC
Labels: duplicate
